[2025-02-09T16:15:01.790+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-09T16:15:01.837+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2025-02-09T16:15:00.506826+00:00 [queued]>
[2025-02-09T16:15:01.847+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2025-02-09T16:15:00.506826+00:00 [queued]>
[2025-02-09T16:15:01.848+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-09T16:15:01.873+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-02-09 16:15:00.506826+00:00
[2025-02-09T16:15:01.885+0000] {standard_task_runner.py:63} INFO - Started process 218 to run task
[2025-02-09T16:15:01.889+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'manual__2025-02-09T16:15:00.506826+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpx7kjbznp']
[2025-02-09T16:15:01.956+0000] {standard_task_runner.py:91} INFO - Job 148: Subtask extract.extract_and_load_to_staging
[2025-02-09T16:15:02.046+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2025-02-09T16:15:00.506826+00:00 [running]> on host 73fe8032b466
[2025-02-09T16:15:02.458+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T16:15:00.506826+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T16:15:00.506826+00:00'
[2025-02-09T16:15:02.461+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-09T16:15:02.536+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-02-09T16:15:02.539+0000] {mysql_operator.py:13} ERROR - Can't connect to mysql database. Error: (2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)")
[2025-02-09T16:15:02.556+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-02-09T16:15:02.558+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-09T16:15:02.560+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_data.py", line 49, in test_extract
    df = source_operator.get_data_to_pd(f"SELECT * FROM {table}")
  File "/opt/airflow/plugins/mysql_operator.py", line 16, in get_data_to_pd
    return self.mysqlhook.get_pandas_df(query)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 262, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)")
[2025-02-09T16:15:02.599+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=manual__2025-02-09T16:15:00.506826+00:00, execution_date=20250209T161500, start_date=20250209T161501, end_date=20250209T161502
[2025-02-09T16:15:02.631+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 148 for task extract.extract_and_load_to_staging ((2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)"); 218)
[2025-02-09T16:15:02.653+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-09T16:15:02.693+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T16:15:02.698+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
