[2025-02-12T10:02:55.952+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-12T10:02:55.986+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.load.transform_fact_orders manual__2025-02-12T10:01:53.320861+00:00 [queued]>
[2025-02-12T10:02:55.999+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.load.transform_fact_orders manual__2025-02-12T10:01:53.320861+00:00 [queued]>
[2025-02-12T10:02:56.000+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-12T10:02:56.016+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load.transform_fact_orders> on 2025-02-12 10:01:53.320861+00:00
[2025-02-12T10:02:56.021+0000] {standard_task_runner.py:63} INFO - Started process 342 to run task
[2025-02-12T10:02:56.025+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'load.transform_fact_orders', 'manual__2025-02-12T10:01:53.320861+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpw45ihzs2']
[2025-02-12T10:02:56.028+0000] {standard_task_runner.py:91} INFO - Job 265: Subtask load.transform_fact_orders
[2025-02-12T10:02:56.082+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.load.transform_fact_orders manual__2025-02-12T10:01:53.320861+00:00 [running]> on host 0cefc44a17d0
[2025-02-12T10:02:56.180+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='load.transform_fact_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T10:01:53.320861+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T10:01:53.320861+00:00'
[2025-02-12T10:02:56.181+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-12T10:02:56.332+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:56.387+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:56.442+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:56.606+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T10:02:57.383+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:57.443+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T10:02:58.351+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:58.436+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T10:02:58.920+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:02:58.987+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-12T10:02:59.729+0000] {logging_mixin.py:188} INFO - Các cột trong DataFrame sau khi merge:
[2025-02-12T10:02:59.731+0000] {logging_mixin.py:188} INFO - Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'customer_zip_code_prefix'],
      dtype='object')
[2025-02-12T10:03:00.063+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-02-12T10:03:07.753+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào fact_orders
[2025-02-12T10:03:07.811+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-12T10:03:07.812+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-12T10:03:07.820+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=load.transform_fact_orders, run_id=manual__2025-02-12T10:01:53.320861+00:00, execution_date=20250212T100153, start_date=20250212T100255, end_date=20250212T100307
[2025-02-12T10:03:07.870+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-12T10:03:07.885+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T10:03:07.888+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
