[2025-02-08T05:11:36.066+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-08T05:11:36.100+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2025-02-08T05:11:34.893745+00:00 [queued]>
[2025-02-08T05:11:36.110+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2025-02-08T05:11:34.893745+00:00 [queued]>
[2025-02-08T05:11:36.111+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-08T05:11:36.127+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-02-08 05:11:34.893745+00:00
[2025-02-08T05:11:36.133+0000] {standard_task_runner.py:63} INFO - Started process 608 to run task
[2025-02-08T05:11:36.137+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'extract.extract_and_load_to_staging', 'manual__2025-02-08T05:11:34.893745+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpouqsu3vh']
[2025-02-08T05:11:36.139+0000] {standard_task_runner.py:91} INFO - Job 123: Subtask extract.extract_and_load_to_staging
[2025-02-08T05:11:36.185+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.extract.extract_and_load_to_staging manual__2025-02-08T05:11:34.893745+00:00 [running]> on host 366ad6feb228
[2025-02-08T05:11:36.270+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T05:11:34.893745+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-08T05:11:34.893745+00:00'
[2025-02-08T05:11:36.271+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-08T05:11:36.409+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-02-08T05:11:40.118+0000] {mysql_operator.py:13} ERROR - Can't connect to mysql database
[2025-02-08T05:11:40.125+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-02-08T05:11:43.837+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-08T05:11:43.838+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_data.py", line 31, in extract_and_load_to_staging
    df = source_operator.get_data_to_pd(f"SELECT * FROM {table}")
  File "/opt/airflow/plugins/mysql_operator.py", line 16, in get_data_to_pd
    return self.mysqlhook.get_pandas_df(query)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 262, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown server host 'mysql' (-2)")
[2025-02-08T05:11:43.851+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=manual__2025-02-08T05:11:34.893745+00:00, execution_date=20250208T051134, start_date=20250208T051136, end_date=20250208T051143
[2025-02-08T05:11:43.863+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 123 for task extract.extract_and_load_to_staging ((2005, "Unknown server host 'mysql' (-2)"); 608)
[2025-02-08T05:11:43.875+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-08T05:11:43.895+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T05:11:43.902+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
